[build]
  command = "npm run build"
  publish = "dist"

[[headers]]
  for = "*.js" # All js files
  [headers.values]
    Cache-Control = "public, max-age=604800"

[[headers]]
  for = "*.css" # All css files
  [headers.values]
    Cache-Control = "public, max-age=604800"

[[headers]]
  for = "*.woff2" # All woff2 files
  [headers.values]
    Cache-Control = "public, max-age=604800"

[[headers]]
  for = "*.webp" # All webp image files
  [headers.values]
    Cache-Control = "public, max-age=604800"

[[headers]]
  for = "*.svg" # All svg image files
  [headers.values]
    Cache-Control = "public, max-age=604800"